spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: guests-service
          uri: lb://guest-service
          predicates:
            - Path=/api/guests/**
        - id: reservations-service
          uri: lb://reservation-service
          predicates:
            - Path=/api/reservations/**
        - id: hotels-service
          uri: lb://hotel-service
          predicates:
            - Path=/api/hotels/**
            - Path=/api/rooms/**
        - id: authentication-service
          uri: lb://authentication-service
          predicates:
          - Path=/api/auth/**
      ignorePatterns:
        - /api/auth**
eureka:
  client:
    healthcheck:
      enabled: true
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_HOST}
  instance:
    hostName: ${spring.application.name}

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 7999


jwt:
  secret: ${JWT_SECRET_KEY}
