spring:
  datasource:
    url: ${GUEST_PROFILE_DB_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  flyway:
    schemas: public
    locations: classpath:db/migration
    enabled: true
jwt:
  secret: ${JWT_SECRET_KEY}

springdoc:
  swagger-ui:
    path: /swagger-ui.html