spring:
  datasource:
    url: ${RESERVATION_DB_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  flyway:
    schemas: public
    locations: classpath:db/migration
    enabled: true
  sleuth:
    sampler:
      percentage: 1.0
  zipkin:
    base-url: ${ZIPKIN_URL}
    sender:
      type: web

eureka:
  client:
    healthcheck:
      enabled: true
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_HOST}
  instance:
    hostName: ${spring.application.name}

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html

hotelService:
  host: ${HOTEL_SERVICE_HOST}
  getAllRoomType: /api/rooms/types

guestService:
  host: ${GUEST_SERVICE_HOST}
  getUserInfo: /api/guest/{id}

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
        recordExceptions:
          - org.springframework.web.client.HttpServerErrorException
          - java.util.concurrent.TimeoutException
          - java.io.IOException
        ignoreExceptions:
          - com.incubator.dbs.reservationservice.exception.ReservationServiceException
      shared:
        slidingWindowSize: 100
        permittedNumberOfCallsInHalfOpenState: 30
        waitDurationInOpenState: 1s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
        ignoreExceptions:
          - com.incubator.dbs.reservationservice.exception.ReservationServiceException
    instances:
      reservations:
        baseConfig: default
  retry:
    configs:
      default:
        maxRetryAttempts: 3
        waitDuration: 100
        retryExceptions:
          - org.springframework.web.client.HttpServerErrorException
          - java.util.concurrent.TimeoutException
          - java.io.IOException
        ignoreExceptions:
          - com.incubator.dbs.reservationservice.exception.ReservationServiceException
    instances:
      reservations:
        baseConfig: default
  bulkhead:
    configs:
      default:
        maxConcurrentCalls: 100
        maxWaitDuration: 10ms
    instances:
      reservations:
        baseConfig: default
  thread-pool-bulkhead:
    configs:
      default:
        maxThreadPoolSize: 4
        coreThreadPoolSize: 2
        queueCapacity: 2
    instances:
      reservations:
        baseConfig: default
  ratelimiter:
    configs:
      default:
        registerHealthIndicator: false
        limitForPeriod: 10
        limitRefreshPeriod: 1s
        timeoutDuration: 0
        eventConsumerBufferSize: 100
    instances:
      reservations:
        baseConfig: default