spring:
  datasource:
    url: ${AUTHENTICATION_DB_URL:jdbc:postgresql://localhost:9000/auth}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:admin}
  flyway:
    schemas: public
    locations: classpath:db/migration
    enabled: true
  sleuth:
    sampler:
      percentage: 1.0
  zipkin:
    base-url: ${ZIPKIN_URL:http://localhost:9411}
    sender:
      type: web
  kafka:
    producer:
      topic: ${KAFKA_TOPIC:create_guest_queue}
      bootstrap-servers: ${KAFKA_SERVER:http://localhost:9092}
      key-serializer: com.incubator.dbs.authenticateservice.model.template.serializer.CreateGuestSerializer
      value-serializer: com.incubator.dbs.authenticateservice.model.template.serializer.CreateGuestSerializer
eureka:
  client:
    healthcheck:
      enabled: true
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_HOST:http://localhost:8761/eureka/}
  instance:
    hostName: ${spring.application.name}

jwt:
  secret: ${JWT_SECRET_KEY:abc@123}

server:
  port: 9084

springdoc:
  swagger-ui:
    path: /swagger-ui.html

guestService:
  host: ${GUEST_SERVICE_HOST:http://localhost:9082}
  createUserProfile: /api/guests

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
        recordExceptions:
          - org.springframework.web.client.HttpServerErrorException
          - java.util.concurrent.TimeoutException
          - java.io.IOException
        ignoreExceptions:
          - com.incubator.dbs.authenticateservice.exception.AuthenticationServiceException
      shared:
        slidingWindowSize: 100
        permittedNumberOfCallsInHalfOpenState: 30
        waitDurationInOpenState: 1s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
        ignoreExceptions:
          - com.incubator.dbs.authenticateservice.exception.AuthenticationServiceException
    instances:
      auth:
        baseConfig: default
  retry:
    configs:
      default:
        maxRetryAttempts: 3
        waitDuration: 100
        retryExceptions:
          - org.springframework.web.client.HttpServerErrorException
          - java.util.concurrent.TimeoutException
          - java.io.IOException
        ignoreExceptions:
          - com.incubator.dbs.authenticateservice.exception.AuthenticationServiceException
    instances:
      auth:
        baseConfig: default
  bulkhead:
    configs:
      default:
        maxConcurrentCalls: 100
        maxWaitDuration: 10ms
      auth:
        baseConfig: default
  thread-pool-bulkhead:
    configs:
      default:
        maxThreadPoolSize: 4
        coreThreadPoolSize: 2
        queueCapacity: 2
    instances:
      auth:
        baseConfig: default
  ratelimiter:
    configs:
      default:
        registerHealthIndicator: false
        limitForPeriod: 10
        limitRefreshPeriod: 1s
        timeoutDuration: 0
        eventConsumerBufferSize: 100
    instances:
      auth:
        baseConfig: default