spring:
  datasource:
    url: ${HOTEL_DB_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  flyway:
    schemas: public
    locations: classpath:db/migration
    enabled: true
  application:
    name: hotel-service
springdoc:
  swagger-ui:
    path: /swagger-ui.html
eureka:
  client:
    healthcheck:
      enabled: true
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_HOST}
  instance:
    hostName: ${spring.application.name}

reservation:
  host: ${RESERVATION_SERVICE_HOST}
  getReservation: /api/reservation

server:
  port: 8081